### ISSUE TITLE
make format more compact

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/data_schema#1]
so, I didn't find a good way how the markdowns are rendered, so we probably would need to move away from the the heading levels. 

Unfortunately, also bullet points take a lot of whitespace

![Screen Shot 2020-11-03 at 13 50 47](https://user-images.githubusercontent.com/32935233/97987471-a8162900-1ddb-11eb-9107-650fc4f894aa.png)

So, the best option is probably to move everything to the same line. 

I'd still aim for something more consistent, that one could potentially parse to a json schema and which other people could then easily reuse. 

I suggest something like

- objectName 
 - attributeName (type, defaultUnit): Description. Possible values: .

My main concern was how to deal with possible values. I think if we always use "Possible values" as introductory clause we should still be fine. 

I still feel that it would make sense to have multiple separate files. e.g., one per spectrum type. 

Do you agree with this, @lpatiny? Or which changes do you suggest? If this is fine, I'll try to go ahead with bringing everything to this format. 

We should probably also keep track of the fields that are currently not used in some separate issue.

**Comment by lpatiny** [comment]
- When we have a list of allowed values we could instead of (string) use ("foo1|foo2|foo3")
- If we have properties of an object we should still use 2 levels of bullets seems to me

- general (object)
  - kind ("catalyst|buffer|cell line|RNA|DNA|molecule|peptide|protein|material)
  - title (string)
  - description (html)
  - purity (number): purity between 0 and 1
  - name (array<object>)
    - value (string)
    - language (string): iso 2 letter code
    - iupac (boolean): flag to determine if iupac name
  - molfile (string)
  - ocl (object)
    - value (string)
    - coordinates (string)
    - index (array<number>)
  - mf (string)
  - mw (number)

**Comment by kjappelbaum** [comment]
ok, thanks for the feedback. 

You are still fine with having multiple documents or do you want to keep all in one long markdown?

**Comment by lpatiny** [comment]
Yes one document per spectra kind is ok for me. This would lead to 20 documents or something like that I guess

**Comment by kjappelbaum** [comment]
What do we do if it is an array of objects? 

I started using `array<{"kind": string, "value": string}>` but this makes it hard to add further description to the elements. Shall we make the convention that in such a case the bullets describe the keys of the object? 

(BTW, I'm starting to open some issues here in this repo with questions about the schema/possible changes ---sorry if I annoy you with that, just let me know).
