### ISSUE TITLE
nmr questions

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/data_schema#19]
- wouldn't it be better to store some chemical information (SMILES?) about the solvent, same for environment
- what is reference? 
- the units in range are ppm? 
- what is dialD
- what is pubintegral, pubAssignment, pubMultiplicity 

- are  dialD (array), pubIntegral (number), kind ("solvent|impurity") only in "signal"? 

- in the ELN some have 'isFID, isFT' as boolean flags. Is this something that is used? 

- does signal also have the delta? (in the ELN some entries have it?) 
- is the remark part of the range object? 

- what are units for x/y/z/width in peak?

**Comment by kjappelbaum** [comment]
reference is a string, e.g., TMS

**Comment by kjappelbaum** [comment]
dialD: diasterotopic id

**Comment by kjappelbaum** [comment]
pubinteg: for publication

**Comment by kjappelbaum** [comment]
kind ("solvent|impurity") only in "signal"?

**Comment by kjappelbaum** [comment]
remark in the signal: HTML

**Comment by kjappelbaum** [comment]
x: chemical shift ppm 
y: relative height 
z: should be used only in 2D and there is a different field for it 
width in Hz

**Comment by kjappelbaum** [comment]
@lpatiny In ethylbenzene on eln.epfl.ch the diasteroptic id only appears in signal and not in range + signal

![Screen Shot 2020-11-10 at 13 56 28](https://user-images.githubusercontent.com/32935233/98676939-9513d380-235c-11eb-97d4-9452b6b8244b.png)

**Comment by kjappelbaum** [comment]
and is "zone" actually used?

**Comment by lpatiny** [comment]
Yes zone is used for 2D nmr
![image](https://user-images.githubusercontent.com/1484241/98799902-01034400-2410-11eb-9b93-48a8f665318b.png)
This is why you have x:from/to and y: from /to
