### ISSUE TITLE
elemental analysis question 

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/data_schema#24]
in ethylbenzene there are also the fields "reference" and "text"  -- do we add this to the schema?  @lpatiny

**Comment by lpatiny** [comment]
text, jcamp, file, pdf are kind of attachments that can be used for all the analysis I think. In the case of elemental analysis it allows to store the document coming from the instrument

For reference I wonder if we use it anywhere else. It would make sense to add also a reference field in which we could store the analytical reference number if it exists

**Comment by kjappelbaum** [comment]
>text, jcamp, file, pdf are kind of attachments that can be used for all the analysis I think
yes, this is what i also found. 

But the question is then maybe rather if we add both `text` and `reference` to all spectra

**Comment by lpatiny** [comment]
I think we may indeed.
