### ISSUE TITLE
remark or remarks ?

### ISSUE THREAD

**Issue by lpatiny** [kjappelbaum/data_schema#32]
Currently we have in reaction the field `remarks` and in the products `remark`.

We should decide which one we prefer.

@kjappelbaum What do you think ? This field is currently not used so we may easily change it.

![image](https://user-images.githubusercontent.com/1484241/107140762-a00edd80-6924-11eb-827e-4cdfe6c2e373.png)

**Comment by kjappelbaum** [comment]
hmm... i tend to the plural form
